# This is a sample docker-compose file that can be used to run Joplin Server
# along with a PostgreSQL server.
#
# Update the following fields in the stanza below:
#
# Application Configuration: 
# APP_BASE_URL: This is the base public URL where the service will be running.
#	- If Joplin Server needs to be accessible over the internet, configure APP_BASE_URL as follows: https://example.com/joplin. 
#	- If Joplin Server does not need to be accessible over the internet, set the APP_BASE_URL to your server's hostname. 
#     For Example: http://[hostname]:22300. The base URL can include the port.
# APP_PORT: The local port on which the Docker container will listen. 
#	- This would typically be mapped to port to 443 (TLS) with a reverse proxy.
#	- If Joplin Server does not need to be accessible over the internet, the port can be mapped to 22300.
# PUID: an optional parameter to specify UID for internal user. `1000` is default value. Right now may be used for beta images only!
# PGID: an optional parameter to specify UID for internal user. `1000` is default value. Right now may be used for beta images only!
#
# DataBase configuration:
# 
# Using PostgreSQL (recommended):
# DB_CLIENT=pg
# POSTGRES_HOST: where is Postgres DB. `db` value in case of compose service.
# POSTGRES_PORT: The port for Postgres DB. A `5432` should be used in most of cases.
# POSTGRES_DATABASE: postgres database to store data. A `joplin` value would be a good chose here.
# POSTGRES_USER: postgres user which has write access to POSTGRES_DATABASE. A `joplin` value would be a good chose here.
# POSTGRES_PASSWORD: The password for POSTGRES_USER. Please generate your own value here.
#
# Using SQLite (not recommended for production, for testing purposes only!)
# DB_CLIENT=sqlite3
# SQLITE_DATABASE: location of local DB file. A `/data/db.sqlite` value would be a good chose here.
#


version: '3'

services:
    db:
        image: postgres:16
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER:-joplin}
            - POSTGRES_DB=${POSTGRES_DATABASE:-joplin}
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE:-joplin}
            - POSTGRES_USER=${POSTGRES_USER:-joplin}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - POSTGRES_HOST=${POSTGRES_HOST:-db}
            - PUID=${PUID:-1000}
            - PGID=${PGID:-1000}
