# =============================================================================
# Build stage
# =============================================================================

FROM node:24 AS builder

# Enables Yarn
RUN --mount=type=cache,target=/root/.cache/node/corepack \
    corepack enable

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \
    && apt-get update \
    && apt-get install -y \
        python3 tini \
        # needed for node-canvas for ARM32 platform.
        # See also https://github.com/Automattic/node-canvas/wiki/Installation:-Ubuntu-and-other-Debian-based-systems  
        libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev


WORKDIR /build

COPY .yarn/releases ./.yarn/releases
COPY .yarn/patches ./.yarn/patches
COPY package.json .
COPY .yarnrc.yml .
COPY yarn.lock .
COPY gulpfile.js .
COPY tsconfig.json .
COPY packages/turndown ./packages/turndown
COPY packages/turndown-plugin-gfm ./packages/turndown-plugin-gfm
COPY packages/fork-htmlparser2 ./packages/fork-htmlparser2
COPY packages/server/package*.json ./packages/server/
COPY packages/fork-sax ./packages/fork-sax
COPY packages/fork-uslug ./packages/fork-uslug
COPY packages/htmlpack ./packages/htmlpack
COPY packages/renderer ./packages/renderer
COPY packages/tools ./packages/tools
COPY packages/utils ./packages/utils
COPY packages/lib ./packages/lib
COPY packages/server ./packages/server

# We don't want to build onenote-converter since it is not used by the server
RUN sed --in-place '/onenote-converter/d' ./packages/lib/package.json


# For some reason there's both a .yarn/cache and .yarn/berry/cache that are
# being generated, and both have the same content. Not clear why it does this
# but we can delete it anyway. We can delete the cache because we use
# `nodeLinker: node-modules`. If we ever implement Zero Install, we'll need to
# keep the cache.
#
# Note that `yarn install` ignores `NODE_ENV=production` and will install dev
# dependencies too, but this is fine because we need them to build the app.

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn \
    --mount=type=cache,target=/root/.yarn/berry/cache \
    --mount=type=cache,target=/root/.npm \
    BUILD_SEQUENCIAL=1 yarn install --inline-builds

# =============================================================================
# Final stage - we copy only the relevant files from the build stage and start
# from a smaller base image.
# =============================================================================

FROM node:24-slim

# Lazy version, https://github.com/tianon/gosu/blob/master/INSTALL.md
COPY --from=tianon/gosu /gosu /usr/local/bin/
COPY --chown=node:node --from=builder /build/packages /app
COPY --from=builder /usr/bin/tini /usr/local/bin/tini
# Entry point to check permissions and switch to node:node user 
COPY --chown=node:node docker/bin/docker-entrypoint.sh /

# We download a specific version of the plugin to prevent pm2 from fetching the latest, since it may
# not have been properly audited (that fact was used to spread malware at some point). Ref:
# https://github.com/laurent22/joplin/issues/12754
RUN pm2 install https://registry.npmjs.org/pm2-logrotate/-/pm2-logrotate-3.0.0.tgz \
	&& pm2 set pm2-logrotate:max_size 100MB \
	&& pm2 set pm2-logrotate:retain 5 \
	&& pm2 set pm2-logrotate:compress true

ENV NODE_ENV=production
ENV RUNNING_IN_DOCKER=1
ENV DATA_ROOT=/data
ENV SRV_ROOT=/app/server
ENV PM2_HOME=$DATA_ROOT/pm2
ENV LOGS_DIR=$DATA_ROOT/logs
ENV TEMP_DIR=$DATA_ROOT/temp

ENV PATH=$PATH:$SRV_ROOT/node_modules/.bin

EXPOSE ${APP_PORT}

RUN chmod ugo+rx,go-w /docker-entrypoint.sh \
    && mkdir -p $PM2_HOME \
    && mkdir -p $LOGS_DIR \
    && mkdir -p $TEMP_DIR \
    && chown node:node -R $DATA_ROOT \
    # In case custom -u UID:GID arg was specified, these directory should be writable for other users
    && chmod og+w $DATA_ROOT \
    && chmod og+w -R $LOGS_DIR \
    && chmod og+w -R $TEMP_DIR

# Use Tini to start Joplin Server:
# https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
WORKDIR $SRV_ROOT

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["pm2-runtime", "--exp-backoff-restart-delay=1000", "dist/app.js"]
